apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    meta.helm.sh/release-name: cert-manager-webhook-dnspod
    meta.helm.sh/release-namespace: cert-manager
  creationTimestamp: "2023-05-09T09:05:51Z"
  labels:
    app: cert-manager-webhook-dnspod
    app.kubernetes.io/managed-by: Helm
    chart: cert-manager-webhook-dnspod-0.3.3
    heritage: Helm
    release: cert-manager-webhook-dnspod
  name: cert-manager-webhook-dnspod:domain-solver
  resourceVersion: "1307"
  uid: 3176b1ad-a473-4133-8cf4-69ab2e4df0cf
rules:
- apiGroups:
  - any.group
  resources:
  - '*'
  verbs:
  - create
