apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRole","metadata":{"annotations":{},"labels":{"app":"cert-manager","app.kubernetes.io/component":"controller","app.kubernetes.io/instance":"cert-manager","app.kubernetes.io/name":"cert-manager","app.kubernetes.io/version":"v1.8.0"},"name":"cert-manager-controller-certificates"},"rules":[{"apiGroups":["cert-manager.io"],"resources":["certificates","certificates/status","certificaterequests","certificaterequests/status"],"verbs":["update","patch"]},{"apiGroups":["cert-manager.io"],"resources":["certificates","certificaterequests","clusterissuers","issuers"],"verbs":["get","list","watch"]},{"apiGroups":["cert-manager.io"],"resources":["certificates/finalizers","certificaterequests/finalizers"],"verbs":["update"]},{"apiGroups":["acme.cert-manager.io"],"resources":["orders"],"verbs":["create","delete","get","list","watch"]},{"apiGroups":[""],"resources":["secrets"],"verbs":["get","list","watch","create","update","delete","patch"]},{"apiGroups":[""],"resources":["events"],"verbs":["create","patch"]}]}
  creationTimestamp: "2023-05-09T09:01:56Z"
  labels:
    app: cert-manager
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/version: v1.8.0
  name: cert-manager-controller-certificates
  resourceVersion: "960"
  uid: b2feae9c-1921-4650-aee3-ff2cd87614bc
rules:
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  - certificates/status
  - certificaterequests
  - certificaterequests/status
  verbs:
  - update
  - patch
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  - certificaterequests
  - clusterissuers
  - issuers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - certificates/finalizers
  - certificaterequests/finalizers
  verbs:
  - update
- apiGroups:
  - acme.cert-manager.io
  resources:
  - orders
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
