apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    objectset.rio.cattle.io/applied: H4sIAAAAAAAA/5SST2/bMAzFv8rA42C7+efVNbDDsMMOu+2wy5ADLbGJZlk0RMpFV+S7D8raLWuaNjnZosgfnt7jA+DovlMUxwFaiB2aCpNuObpfqI5D1TdSOb6a5lBA74KFFj77JErxG3uCAgZStKgI7QNgCKz7OclH7n6SUSGtouPKoKqnDHOZAsXJe74LFMvN1EML/VIObqZ58e6rC/bjJ2s5vIkIOBC0YMxwVquMaHJ/nzoq5V6UBtgV4LEj/+qDtihbaKGeNTerD029qk29ahar+dJc385qapbXdNM1ze1sgXZWLzL0UVq/lNJ4TrY0HDSy9xTLAQNuKOa2mDwJtD/2QX2JnMZ8AsMcrQuHEcG6gEjCKZr9BHhCIcnliWK3L21IoQATCTVHl0abf9a74hn+iEUTBf2f9ZcyoprtRbTA9pmw92ePXYmiJoEChOLkzL/KIe+PpjOYT5D8DrYvueWd5M/dxcRjPZd49IhBYzidtD4rPMe4p92+CIPjKEcoizRwENK387NODE8U708tKAU7sgsq/sivF61f734HAAD//7yP5LevBAAA
    objectset.rio.cattle.io/id: ""
    objectset.rio.cattle.io/owner-gvk: k3s.cattle.io/v1, Kind=Addon
    objectset.rio.cattle.io/owner-name: ccm
    objectset.rio.cattle.io/owner-namespace: kube-system
  creationTimestamp: "2023-05-09T08:59:35Z"
  labels:
    objectset.rio.cattle.io/hash: 5089468545c5482413c7f05e837e9b88f02ad052
  name: k3s-cloud-controller-manager
  resourceVersion: "304"
  uid: a18ed558-fc5c-425a-944f-9b329f3e28cb
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - create
  - update
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - nodes/status
  - services/status
  verbs:
  - patch
- apiGroups:
  - ""
  resources:
  - services
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - get
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - get
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - '*'
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - get
  - list
  - watch
