apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: "2023-05-09T09:22:46Z"
  labels:
    kots.io/backup: velero
    kots.io/kotsadm: "true"
  name: kotsadm-role
  resourceVersion: "2604"
  uid: 9918940c-630c-4430-b38c-00be11aa4417
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
