apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    objectset.rio.cattle.io/applied: H4sIAAAAAAAA/4ySMY/bMAyF/0rBsZDdpE4Cw0CHokOHbh26FBloiY5Vy6Ig0j60h/z3QkaGO7R3l0mgHt5HUk+PgMn/oCyeI3SQe7Q1Ljpy9n9QPcd6aqX2/GHdg4HJRwcdfAmLKOXvHAgMzKToUBG6R8AYWTeflJL7X2RVSOvsubaoGqjAfKGAeVHnh0i5uqwTdDA18kRZ9+bdNx/dp8/OcXwTEXEm6CCwxVCJcsYL3WWShLY4p6WnSn6L0gxXAwF7Cq+uNqKM0MG+bYbmaE/HYehtszsdTrtmODTD/tjuXGtPLX502LtDgT4bMqGOVcq8+hIJ5SqXV74ayEsgge7nltjXzEsqFcDZQCbhJdtNhsiOBAykEqooRV05LDPZgH4uguU4+MuMSYp3pdxvvgspGAheyvGAakc4X81b3Si6xD7q/zpud+yet3l/F3Wlgnzqs5lQS3bphdFu6d7+6z/Im2wDitAdm5+vfwMAAP//OqHYBhsDAAA
    objectset.rio.cattle.io/id: ""
    objectset.rio.cattle.io/owner-gvk: k3s.cattle.io/v1, Kind=Addon
    objectset.rio.cattle.io/owner-name: local-storage
    objectset.rio.cattle.io/owner-namespace: kube-system
  creationTimestamp: "2023-05-09T08:59:35Z"
  labels:
    objectset.rio.cattle.io/hash: 183f35c65ffbc3064603f43f1580d8c68a2dabd4
  name: local-path-provisioner-role
  resourceVersion: "324"
  uid: 50870e7e-0a99-4edc-82f2-da7394fa28b7
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - persistentvolumeclaims
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - endpoints
  - persistentvolumes
  - pods
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
  - watch
