apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: "2023-05-09T08:59:31Z"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:kube-aggregator
  resourceVersion: "89"
  uid: c356798b-3d52-4fde-9cc8-be25da7b32c5
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  - services
  verbs:
  - get
  - list
  - watch
