apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    meta.helm.sh/release-name: gitpod
    meta.helm.sh/release-namespace: gitpod
  creationTimestamp: "2023-05-09T09:31:14Z"
  labels:
    app: gitpod
    app.kubernetes.io/managed-by: Helm
    component: agent-smith
  name: agent-smith
  namespace: gitpod
  resourceVersion: "3563"
  uid: 6e9865a7-05ff-4f04-8f90-87696de0c2a2
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - update
