apiVersion: v1
kind: ResourceQuota
metadata:
  annotations:
    meta.helm.sh/release-name: gitpod
    meta.helm.sh/release-namespace: gitpod
  creationTimestamp: "2023-05-09T09:31:13Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: gitpod-resource-quota
  namespace: gitpod
  resourceVersion: "8411"
  uid: 187b2b05-1d1c-49da-b35f-d517fadaaad1
spec:
  hard:
    pods: 10k
  scopeSelector:
    matchExpressions:
    - operator: In
      scopeName: PriorityClass
      values:
      - system-node-critical
status:
  hard:
    pods: 10k
  used:
    pods: "7"
