apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRoleBinding","metadata":{"annotations":{},"labels":{"app":"webhook","app.kubernetes.io/component":"webhook","app.kubernetes.io/instance":"cert-manager","app.kubernetes.io/name":"webhook","app.kubernetes.io/version":"v1.8.0"},"name":"cert-manager-webhook:subjectaccessreviews"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"ClusterRole","name":"cert-manager-webhook:subjectaccessreviews"},"subjects":[{"apiGroup":"","kind":"ServiceAccount","name":"cert-manager-webhook","namespace":"cert-manager"}]}
  creationTimestamp: "2023-05-09T09:01:56Z"
  labels:
    app: webhook
    app.kubernetes.io/component: webhook
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/name: webhook
    app.kubernetes.io/version: v1.8.0
  name: cert-manager-webhook:subjectaccessreviews
  resourceVersion: "985"
  uid: d6d7f610-40f8-4ef0-a3b4-eeaeec12ce1d
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-webhook:subjectaccessreviews
subjects:
- kind: ServiceAccount
  name: cert-manager-webhook
  namespace: cert-manager
