apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    meta.helm.sh/release-name: gitpod
    meta.helm.sh/release-namespace: gitpod
  creationTimestamp: "2023-05-09T09:31:14Z"
  labels:
    app: gitpod
    app.kubernetes.io/managed-by: Helm
    component: server
  name: gitpod-server-rb-kube-rbac-proxy
  resourceVersion: "3542"
  uid: 370404e0-c982-4675-ae8f-f7835602b50c
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gitpod-kube-rbac-proxy
subjects:
- kind: ServiceAccount
  name: server
  namespace: gitpod
