apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    meta.helm.sh/release-name: gitpod
    meta.helm.sh/release-namespace: gitpod
  creationTimestamp: "2023-05-09T09:31:14Z"
  labels:
    app: gitpod
    app.kubernetes.io/managed-by: Helm
    component: public-api-server
  name: gitpod-public-api-server-rb-kube-rbac-proxy
  resourceVersion: "3547"
  uid: 645f0f18-bdd9-427b-8793-a471edc0323c
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gitpod-kube-rbac-proxy
subjects:
- kind: ServiceAccount
  name: public-api-server
  namespace: gitpod
