apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    meta.helm.sh/release-name: gitpod
    meta.helm.sh/release-namespace: gitpod
  creationTimestamp: "2023-05-09T09:31:14Z"
  labels:
    app: gitpod
    app.kubernetes.io/managed-by: Helm
    component: registry-facade
  name: gitpod-registry-facade-rb
  resourceVersion: "3545"
  uid: f3c498a6-f9b6-47e5-a964-83012b0201f8
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gitpod-ns-registry-facade
subjects:
- kind: ServiceAccount
  name: registry-facade
  namespace: gitpod
