apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    objectset.rio.cattle.io/applied: H4sIAAAAAAAA/4yRQU/DMAyF/wryuS3d2rIuEgfgwIHbJLggDm7idaFpXCXpEEz77yjbQEiMsaPl589+fhvAQT+R85otCHANygzHsGKnPzBotllX+0zz5XoCCXTaKhBwZ0YfyC3Y0K22StsWEugpoMKAIDaA1nLYjftYcvNKMngKmdOcSQzBUGTqCIPkzz6/WXJpu+5AQFf4H531JLl40FZd3yjF9l+ExZ5AgJT9WVI/oIz6bmwo9e8+UA/bBAw2ZE4aWqFfgYAqr+flVV2VlazKelpOCjlb5hXVxYzmTV0v8ymqvJpG6OG0rvCpNDyqVLINjo0hl/ZosSWXxkBSRYZaDOzilGNDC1rufj3oe8fjcCq9o9HB9/K9RfF7jR/3RkE8b74Ij54cnHX3QXX0my/bzwAAAP//uYQ87HoCAAA
    objectset.rio.cattle.io/id: ""
    objectset.rio.cattle.io/owner-gvk: k3s.cattle.io/v1, Kind=Addon
    objectset.rio.cattle.io/owner-name: ccm
    objectset.rio.cattle.io/owner-namespace: kube-system
  creationTimestamp: "2023-05-09T08:59:35Z"
  labels:
    objectset.rio.cattle.io/hash: 5089468545c5482413c7f05e837e9b88f02ad052
  name: k3s-cloud-controller-manager-auth-delegator
  resourceVersion: "306"
  uid: fe3b3c5c-2b0f-4d53-af5a-7bce01ff9520
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: k3s-cloud-controller-manager
  namespace: kube-system
