apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: "2023-05-09T08:59:32Z"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:controller:job-controller
  resourceVersion: "159"
  uid: 1c4ed9ce-ec0c-43d5-82cf-ba5b925ae51a
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:controller:job-controller
subjects:
- kind: ServiceAccount
  name: job-controller
  namespace: kube-system
