apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: "2023-05-09T08:59:32Z"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:controller:ttl-controller
  resourceVersion: "171"
  uid: 0414576e-695d-4c7e-9170-896c9ebac2c1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:controller:ttl-controller
subjects:
- kind: ServiceAccount
  name: ttl-controller
  namespace: kube-system
