apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: "2023-05-09T08:59:32Z"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:controller:deployment-controller
  resourceVersion: "150"
  uid: e4902653-c245-4324-90c1-0f87e202f3c1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:controller:deployment-controller
subjects:
- kind: ServiceAccount
  name: deployment-controller
  namespace: kube-system
