apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: "2023-05-09T08:59:32Z"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:controller:service-account-controller
  resourceVersion: "168"
  uid: b97722e0-a077-4794-ba2a-a340d1634e84
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:controller:service-account-controller
subjects:
- kind: ServiceAccount
  name: service-account-controller
  namespace: kube-system
