apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: rancher.io/local-path
  creationTimestamp: "2023-05-09T09:31:37Z"
  finalizers:
  - kubernetes.io/pv-protection
  name: pvc-c539eb32-b6cb-4c95-aa50-02ad5cd4982d
  resourceVersion: "4368"
  uid: ff91d19d-99ad-4ac7-88c2-50bff871f356
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 8Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: minio
    namespace: gitpod
    resourceVersion: "3846"
    uid: c539eb32-b6cb-4c95-aa50-02ad5cd4982d
  hostPath:
    path: /var/lib/rancher/k3s/storage/pvc-c539eb32-b6cb-4c95-aa50-02ad5cd4982d_gitpod_minio
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - vultr
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-path
  volumeMode: Filesystem
status:
  phase: Bound
