apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: rancher.io/local-path
  creationTimestamp: "2023-05-09T09:22:06Z"
  finalizers:
  - kubernetes.io/pv-protection
  name: pvc-7d94c3b4-d224-44cb-b04a-297c63c97d72
  resourceVersion: "2515"
  uid: c838a5b8-58bd-4d9b-9ca9-864ebc9d63af
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 4Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: kotsadm-minio-kotsadm-minio-0
    namespace: gitpod
    resourceVersion: "2450"
    uid: 7d94c3b4-d224-44cb-b04a-297c63c97d72
  hostPath:
    path: /var/lib/rancher/k3s/storage/pvc-7d94c3b4-d224-44cb-b04a-297c63c97d72_gitpod_kotsadm-minio-kotsadm-minio-0
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - vultr
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-path
  volumeMode: Filesystem
status:
  phase: Bound
