apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: rancher.io/local-path
  creationTimestamp: "2023-05-09T09:31:40Z"
  finalizers:
  - kubernetes.io/pv-protection
  name: pvc-f8b64680-9af5-458e-9287-6852543c6f4e
  resourceVersion: "4410"
  uid: b8d92cd2-0839-409e-9712-85310f7f1dab
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 8Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: redis-data-openvsx-proxy-0
    namespace: gitpod
    resourceVersion: "3881"
    uid: f8b64680-9af5-458e-9287-6852543c6f4e
  hostPath:
    path: /var/lib/rancher/k3s/storage/pvc-f8b64680-9af5-458e-9287-6852543c6f4e_gitpod_redis-data-openvsx-proxy-0
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - vultr
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-path
  volumeMode: Filesystem
status:
  phase: Bound
