apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: gitpod
    meta.helm.sh/release-namespace: gitpod
  creationTimestamp: "2023-05-09T09:31:13Z"
  labels:
    app: gitpod
    app.kubernetes.io/managed-by: Helm
    component: docker-registry
  name: docker-registry
  namespace: gitpod
  resourceVersion: "3477"
  uid: e4c8db52-7984-4bcb-9704-9213d23df72e
