apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: gitpod
    meta.helm.sh/release-namespace: gitpod
  creationTimestamp: "2023-05-09T09:31:13Z"
  labels:
    app: gitpod
    app.kubernetes.io/managed-by: Helm
    component: nobody
  name: nobody
  namespace: gitpod
  resourceVersion: "3478"
  uid: cd3f5340-2139-4663-b8c8-6c56f4e27922
