apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: gitpod
    meta.helm.sh/release-namespace: gitpod
  creationTimestamp: "2023-05-09T09:31:13Z"
  labels:
    app: gitpod
    app.kubernetes.io/managed-by: Helm
    component: public-api-server
  name: public-api-server
  namespace: gitpod
  resourceVersion: "3476"
  uid: d5123422-a344-4291-a342-1b46b0e181dc
