apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: gitpod
    meta.helm.sh/release-namespace: gitpod
  creationTimestamp: "2023-05-09T09:31:13Z"
  labels:
    app.kubernetes.io/instance: rabbitmq
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: rabbitmq
    helm.sh/chart: rabbitmq-11.3.0
  name: rabbitmq
  namespace: gitpod
  resourceVersion: "3479"
  uid: ac53bfb8-9c63-4145-aed0-9c77dcc9d2e8
secrets:
- name: messagebus
