apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: gitpod
    meta.helm.sh/release-namespace: gitpod
  creationTimestamp: "2023-05-09T09:31:13Z"
  labels:
    app: gitpod
    app.kubernetes.io/managed-by: Helm
    component: registry-facade
  name: registry-facade
  namespace: gitpod
  resourceVersion: "3491"
  uid: 5d356369-c014-446d-a272-f29eb3e53275
