apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: gitpod
    meta.helm.sh/release-namespace: gitpod
  creationTimestamp: "2023-05-09T09:31:13Z"
  labels:
    app: gitpod
    app.kubernetes.io/managed-by: Helm
    component: ws-manager
  name: ws-manager
  namespace: gitpod
  resourceVersion: "3498"
  uid: 3563e5ac-1a6f-4163-9dc0-b2a0dac0775e
