apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: gitpod
    meta.helm.sh/release-namespace: gitpod
  creationTimestamp: "2023-05-09T09:31:13Z"
  labels:
    app: gitpod
    app.kubernetes.io/managed-by: Helm
    component: ws-manager-bridge
  name: ws-manager-bridge
  namespace: gitpod
  resourceVersion: "3493"
  uid: aae82ca9-c2df-4337-b3e8-889cce213718
