apiVersion: v1
data:
  custom_parsers.conf: |
    [PARSER]
        Name docker_no_time
        Format json
        Time_Keep Off
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
  fluent-bit.conf: |
    [SERVICE]
        Daemon Off
        Flush 1
        Log_Level info
        Parsers_File parsers.conf
        Parsers_File custom_parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port 2020
        Health_Check On

    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        Parser docker
        Tag <pod_name>.<container_name>
        Tag_Regex (?<pod_name>[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<namespace_name>[^_]+)_(?<container_name>.+)-
        Skip_Long_Lines On

    [FILTER]
        Name stdout

    [OUTPUT]
        Name file
        Match imagebuild*
        Mkdir true
        Path /gitpod/log-collector
        Format plain

    [OUTPUT]
        Name file
        Match installer*
        Mkdir true
        Path /gitpod/log-collector
        Format plain

    [OUTPUT]
        Name file
        Match migrations*
        Mkdir true
        Path /gitpod/log-collector
        Format plain

    # Workspaces
    [OUTPUT]
        Name file
        Match ws*.workspace
        Mkdir true
        Path /gitpod/log-collector
        Format plain
kind: ConfigMap
metadata:
  annotations:
    kots.io/app-slug: gitpod
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"custom_parsers.conf":"[PARSER]\n    Name docker_no_time\n    Format json\n    Time_Keep Off\n    Time_Key time\n    Time_Format %Y-%m-%dT%H:%M:%S.%L\n","fluent-bit.conf":"[SERVICE]\n    Daemon Off\n    Flush 1\n    Log_Level info\n    Parsers_File parsers.conf\n    Parsers_File custom_parsers.conf\n    HTTP_Server On\n    HTTP_Listen 0.0.0.0\n    HTTP_Port 2020\n    Health_Check On\n\n[INPUT]\n    Name tail\n    Path /var/log/containers/*.log\n    Parser docker\n    Tag \u003cpod_name\u003e.\u003ccontainer_name\u003e\n    Tag_Regex (?\u003cpod_name\u003e[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?\u003cnamespace_name\u003e[^_]+)_(?\u003ccontainer_name\u003e.+)-\n    Skip_Long_Lines On\n\n[FILTER]\n    Name stdout\n\n[OUTPUT]\n    Name file\n    Match imagebuild*\n    Mkdir true\n    Path /gitpod/log-collector\n    Format plain\n\n[OUTPUT]\n    Name file\n    Match installer*\n    Mkdir true\n    Path /gitpod/log-collector\n    Format plain\n\n[OUTPUT]\n    Name file\n    Match migrations*\n    Mkdir true\n    Path /gitpod/log-collector\n    Format plain\n\n# Workspaces\n[OUTPUT]\n    Name file\n    Match ws*.workspace\n    Mkdir true\n    Path /gitpod/log-collector\n    Format plain\n"},"kind":"ConfigMap","metadata":{"annotations":{"kots.io/app-slug":"gitpod"},"labels":{"app.kubernetes.io/instance":"fluent-bit","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"fluent-bit","app.kubernetes.io/version":"1.9.4","helm.sh/chart":"fluent-bit-0.20.2","kots.io/app-slug":"gitpod","kots.io/backup":"velero"},"name":"fluent-bit","namespace":"gitpod"}}
  creationTimestamp: "2023-05-09T09:30:53Z"
  labels:
    app.kubernetes.io/instance: fluent-bit
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/version: 1.9.4
    helm.sh/chart: fluent-bit-0.20.2
    kots.io/app-slug: gitpod
    kots.io/backup: velero
  name: fluent-bit
  namespace: gitpod
  resourceVersion: "3272"
  uid: 32dc3689-f0f3-49be-9609-13a5aca83f5b
