apiVersion: v1
data:
  channelName: Stable
  cursor: "27"
  isAirgap: "false"
  releaseNotes: ""
  sequence: "1"
  version: 2022.11.2
kind: ConfigMap
metadata:
  annotations:
    kots.io/app-slug: gitpod
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"channelName":"Stable","cursor":"27","isAirgap":"false","releaseNotes":"","sequence":"1","version":"2022.11.2"},"kind":"ConfigMap","metadata":{"annotations":{"kots.io/app-slug":"gitpod"},"labels":{"app":"gitpod","component":"gitpod-installer","kots.io/app-slug":"gitpod","kots.io/backup":"velero"},"name":"gitpod-installation","namespace":"gitpod"}}
  creationTimestamp: "2023-05-09T09:30:54Z"
  labels:
    app: gitpod
    component: gitpod-installer
    kots.io/app-slug: gitpod
    kots.io/backup: velero
  name: gitpod-installation
  namespace: gitpod
  resourceVersion: "7512"
  uid: 8ff2461c-751a-4f77-aa46-bb9ba6592943
