apiVersion: v1
data:
  app-version-label: ""
  ensure-rbac: "true"
  initial-app-images-pushed: "false"
  kots-install-id: 2PYBPgqqVdRdn12kvBqesNkukdl
  minio-enabled-snapshots: "true"
  registry-is-read-only: "false"
  skip-compatibility-check: "false"
  skip-preflights: "false"
  skip-rbac-check: "false"
  strict-security-context: "false"
  use-minimal-rbac: "false"
  wait-duration: 2m0s
  with-minio: "true"
kind: ConfigMap
metadata:
  creationTimestamp: "2023-05-09T09:21:56Z"
  labels:
    kots.io/backup: velero
    kots.io/kotsadm: "true"
  name: kotsadm-confg
  namespace: gitpod
  resourceVersion: "2421"
  uid: 7bd75cb1-2896-4f29-bdc8-5cd555376fb3
