apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    meta.helm.sh/release-name: gitpod
    meta.helm.sh/release-namespace: gitpod
  creationTimestamp: "2023-05-09T09:31:14Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: gitpod-ns-nobody
  namespace: gitpod
  resourceVersion: "3570"
  uid: 2b4facfc-c26d-4a64-812d-f48c948c3a26
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gitpod-ns-psp:unprivileged
subjects:
- kind: ServiceAccount
  name: nobody
  namespace: gitpod
