apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    meta.helm.sh/release-name: gitpod
    meta.helm.sh/release-namespace: gitpod
  creationTimestamp: "2023-05-09T09:31:14Z"
  labels:
    app: gitpod
    app.kubernetes.io/managed-by: Helm
    component: image-builder-mk3
  name: image-builder-mk3
  namespace: gitpod
  resourceVersion: "3571"
  uid: e840e2eb-c9c8-4b23-96b6-08eff8a17f18
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gitpod-ns-image-builder-mk3
subjects:
- kind: ServiceAccount
  name: image-builder-mk3
