apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    meta.helm.sh/release-name: gitpod
    meta.helm.sh/release-namespace: gitpod
  creationTimestamp: "2023-05-09T09:31:14Z"
  labels:
    app: gitpod
    app.kubernetes.io/managed-by: Helm
    component: minio
  name: minio
  namespace: gitpod
  resourceVersion: "3588"
  uid: db1def65-598d-485b-8fd1-4535576a56aa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gitpod-ns-psp:unprivileged
subjects:
- kind: ServiceAccount
  name: minio
