apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    meta.helm.sh/release-name: gitpod
    meta.helm.sh/release-namespace: gitpod
  creationTimestamp: "2023-05-09T09:31:14Z"
  labels:
    app: gitpod
    app.kubernetes.io/managed-by: Helm
    component: proxy
  name: proxy
  namespace: gitpod
  resourceVersion: "3575"
  uid: bd0e2911-43e8-4d6a-ac1a-9bde167efcaf
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gitpod-ns-psp:restricted-root-user
subjects:
- kind: ServiceAccount
  name: proxy
