apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
    volume.kubernetes.io/selected-node: vultr
    volume.kubernetes.io/storage-provisioner: rancher.io/local-path
  creationTimestamp: "2023-05-09T09:21:56Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: kotsadm-minio
    kots.io/backup: velero
    kots.io/kotsadm: "true"
  name: kotsadm-minio-kotsadm-minio-0
  namespace: gitpod
  resourceVersion: "2517"
  uid: 7d94c3b4-d224-44cb-b04a-297c63c97d72
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: local-path
  volumeMode: Filesystem
  volumeName: pvc-7d94c3b4-d224-44cb-b04a-297c63c97d72
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 4Gi
  phase: Bound
