apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
    volume.kubernetes.io/selected-node: vultr
    volume.kubernetes.io/storage-provisioner: rancher.io/local-path
  creationTimestamp: "2023-05-09T09:21:56Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: kotsadm-rqlite
    kots.io/backup: velero
    kots.io/kotsadm: "true"
  name: kotsadm-rqlite-kotsadm-rqlite-0
  namespace: gitpod
  resourceVersion: "2514"
  uid: 94bd21cc-c22b-45dc-8967-3e03f45345d9
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
  volumeMode: Filesystem
  volumeName: pvc-94bd21cc-c22b-45dc-8967-3e03f45345d9
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  phase: Bound
