apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
    volume.kubernetes.io/selected-node: vultr
    volume.kubernetes.io/storage-provisioner: rancher.io/local-path
  creationTimestamp: "2023-05-09T09:31:14Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: gitpod
    component: openvsx-proxy
  name: redis-data-openvsx-proxy-0
  namespace: gitpod
  resourceVersion: "4413"
  uid: f8b64680-9af5-458e-9287-6852543c6f4e
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: local-path
  volumeMode: Filesystem
  volumeName: pvc-f8b64680-9af5-458e-9287-6852543c6f4e
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 8Gi
  phase: Bound
