apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    meta.helm.sh/release-name: gitpod
    meta.helm.sh/release-namespace: gitpod
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
    volume.kubernetes.io/selected-node: vultr
    volume.kubernetes.io/storage-provisioner: rancher.io/local-path
  creationTimestamp: "2023-05-09T09:31:14Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: registry
    app.kubernetes.io/managed-by: Helm
    chart: docker-registry-2.2.2
    heritage: Helm
    release: docker-registry
  name: registry
  namespace: gitpod
  resourceVersion: "4314"
  uid: f069f149-9036-4c7e-ab24-d13cea868da5
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
  volumeMode: Filesystem
  volumeName: pvc-f069f149-9036-4c7e-ab24-d13cea868da5
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  phase: Bound
