addressType: IPv4
apiVersion: discovery.k8s.io/v1
endpoints:
- addresses:
  - 192.168.132.227
  conditions:
    ready: true
    serving: true
    terminating: false
  nodeName: vultr
  targetRef:
    kind: Pod
    name: messagebus-0
    namespace: gitpod
    uid: 869142aa-edfa-459c-97ee-4ef724ddc1ec
kind: EndpointSlice
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2023-05-09T10:14:05Z"
  creationTimestamp: "2023-05-09T09:31:14Z"
  generateName: messagebus-
  generation: 11
  labels:
    app.kubernetes.io/instance: rabbitmq
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: rabbitmq
    endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
    helm.sh/chart: rabbitmq-11.3.0
    kubernetes.io/service-name: messagebus
  name: messagebus-8q2cd
  namespace: gitpod
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: Service
    name: messagebus
    uid: 752f393d-d2a0-4ac4-b6cd-0b2935109a31
  resourceVersion: "9198"
  uid: 70ecfd71-98ff-4b5f-b805-7211c9258e32
ports:
- name: epmd
  port: 4369
  protocol: TCP
- name: metrics
  port: 9419
  protocol: TCP
- name: amqp
  port: 5672
  protocol: TCP
- name: dist
  port: 25672
  protocol: TCP
- name: amqp-ssl
  port: 5671
  protocol: TCP
- name: http-stats
  port: 15672
  protocol: TCP
