addressType: IPv4
apiVersion: discovery.k8s.io/v1
endpoints:
- addresses:
  - 192.168.132.227
  conditions:
    ready: true
    serving: true
    terminating: false
  hostname: messagebus-0
  nodeName: vultr
  targetRef:
    kind: Pod
    name: messagebus-0
    namespace: gitpod
    uid: 869142aa-edfa-459c-97ee-4ef724ddc1ec
kind: EndpointSlice
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2023-05-09T10:14:05Z"
  creationTimestamp: "2023-05-09T09:31:14Z"
  generateName: messagebus-headless-
  generation: 11
  labels:
    app.kubernetes.io/instance: rabbitmq
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: rabbitmq
    endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
    helm.sh/chart: rabbitmq-11.3.0
    kubernetes.io/service-name: messagebus-headless
    service.kubernetes.io/headless: ""
  name: messagebus-headless-9bmxx
  namespace: gitpod
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: Service
    name: messagebus-headless
    uid: 7c44d77b-4fcf-448d-ac46-69df3cee3e3c
  resourceVersion: "9200"
  uid: a9544ad3-e5b2-4e2f-9c8e-a18f90263f59
ports:
- name: epmd
  port: 4369
  protocol: TCP
- name: amqp
  port: 5672
  protocol: TCP
- name: dist
  port: 25672
  protocol: TCP
- name: http-stats
  port: 15672
  protocol: TCP
