apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
    meta.helm.sh/release-name: gitpod
    meta.helm.sh/release-namespace: gitpod
  creationTimestamp: "2023-05-09T09:31:15Z"
  generation: 1
  labels:
    app: gitpod
    app.kubernetes.io/managed-by: Helm
    component: cluster
  name: ca-issuer-ca
  namespace: gitpod
  resourceVersion: "4054"
  uid: 01cddd70-1733-4e2d-8bbb-580a085da806
spec:
  commonName: ca-issuer-ca
  duration: 2160h0m0s
  isCA: true
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: gitpod-selfsigned-issuer
  privateKey:
    algorithm: ECDSA
    size: 256
  secretName: ca-issuer-ca
  secretTemplate:
    labels:
      app: gitpod
      component: cluster
status:
  conditions:
  - lastTransitionTime: "2023-05-09T09:31:16Z"
    message: Certificate is up to date and has not expired
    observedGeneration: 1
    reason: Ready
    status: "True"
    type: Ready
  notAfter: "2023-08-07T09:31:15Z"
  notBefore: "2023-05-09T09:31:15Z"
  renewalTime: "2023-07-08T09:31:15Z"
  revision: 1
