apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
    meta.helm.sh/release-name: gitpod
    meta.helm.sh/release-namespace: gitpod
  creationTimestamp: "2023-05-09T09:31:15Z"
  generation: 1
  labels:
    app: gitpod
    app.kubernetes.io/managed-by: Helm
    component: ws-manager
  name: ws-manager
  namespace: gitpod
  resourceVersion: "4134"
  uid: 66b5b24d-ada0-405b-9f3a-72e0f5876a9d
spec:
  dnsNames:
  - registry-facade
  - server
  - ws-manager-bridge
  - ws-proxy
  - ws-manager
  duration: 2160h0m0s
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: ca-issuer
  secretName: ws-manager-client-tls
  secretTemplate:
    labels:
      app: gitpod
      component: ws-manager
status:
  conditions:
  - lastTransitionTime: "2023-05-09T09:31:20Z"
    message: Certificate is up to date and has not expired
    observedGeneration: 1
    reason: Ready
    status: "True"
    type: Ready
  notAfter: "2023-08-07T09:31:20Z"
  notBefore: "2023-05-09T09:31:20Z"
  renewalTime: "2023-07-08T09:31:20Z"
  revision: 1
