apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
    meta.helm.sh/release-name: gitpod
    meta.helm.sh/release-namespace: gitpod
  creationTimestamp: "2023-05-09T09:31:15Z"
  generation: 1
  labels:
    app: gitpod
    app.kubernetes.io/managed-by: Helm
    component: ws-manager
  name: ws-manager-tls
  namespace: gitpod
  resourceVersion: "4135"
  uid: 9e663804-f6a0-45c6-9af1-95e363a4af6c
spec:
  dnsNames:
  - gitpod.gitpod
  - ws-manager.gitpod.svc
  - ws-manager
  - ws-manager-dev
  duration: 2160h0m0s
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: ca-issuer
  secretName: ws-manager-tls
  secretTemplate:
    labels:
      app: gitpod
      component: ws-manager
status:
  conditions:
  - lastTransitionTime: "2023-05-09T09:31:20Z"
    message: Certificate is up to date and has not expired
    observedGeneration: 1
    reason: Ready
    status: "True"
    type: Ready
  notAfter: "2023-08-07T09:31:20Z"
  notBefore: "2023-05-09T09:31:20Z"
  renewalTime: "2023-07-08T09:31:20Z"
  revision: 1
