apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: gitpod
    meta.helm.sh/release-namespace: gitpod
  creationTimestamp: "2023-05-09T09:31:14Z"
  labels:
    app: gitpod
    app.kubernetes.io/managed-by: Helm
    component: content-service
    kind: service
  name: content-service
  namespace: gitpod
  resourceVersion: "3601"
  uid: 3d2ac83f-ec7b-46ce-86c1-0fe2c178e0a6
spec:
  clusterIP: 10.43.13.102
  clusterIPs:
  - 10.43.13.102
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: rpc
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: metrics
    port: 9500
    protocol: TCP
    targetPort: 9500
  selector:
    app: gitpod
    component: content-service
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
