apiVersion: v1
kind: Service
metadata:
  annotations:
    kots.io/app-slug: gitpod
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"kots.io/app-slug":"gitpod"},"labels":{"app.kubernetes.io/instance":"fluent-bit","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"fluent-bit","app.kubernetes.io/version":"1.9.4","helm.sh/chart":"fluent-bit-0.20.2","kots.io/app-slug":"gitpod","kots.io/backup":"velero"},"name":"fluent-bit","namespace":"gitpod"},"spec":{"ports":[{"name":"http","port":2020,"protocol":"TCP","targetPort":"http"}],"selector":{"app.kubernetes.io/instance":"fluent-bit","app.kubernetes.io/name":"fluent-bit"},"type":"ClusterIP"}}
  creationTimestamp: "2023-05-09T09:30:56Z"
  labels:
    app.kubernetes.io/instance: fluent-bit
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/version: 1.9.4
    helm.sh/chart: fluent-bit-0.20.2
    kots.io/app-slug: gitpod
    kots.io/backup: velero
  name: fluent-bit
  namespace: gitpod
  resourceVersion: "3279"
  uid: 1d2398f0-60e3-41c3-839e-e975b36fe966
spec:
  clusterIP: 10.43.34.200
  clusterIPs:
  - 10.43.34.200
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 2020
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: fluent-bit
    app.kubernetes.io/name: fluent-bit
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
