apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: gitpod
    meta.helm.sh/release-namespace: gitpod
  creationTimestamp: "2023-05-09T09:31:14Z"
  labels:
    app: gitpod
    app.kubernetes.io/managed-by: Helm
    component: ide-service
    kind: service
  name: ide-service
  namespace: gitpod
  resourceVersion: "3613"
  uid: 53bf1a1b-98bf-4b20-82c1-521af28899b0
spec:
  clusterIP: 10.43.217.238
  clusterIPs:
  - 10.43.217.238
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: grpc
    port: 9001
    protocol: TCP
    targetPort: 9001
  selector:
    app: gitpod
    component: ide-service
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
