apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: gitpod
    meta.helm.sh/release-namespace: gitpod
  creationTimestamp: "2023-05-09T09:31:14Z"
  labels:
    app: gitpod
    app.kubernetes.io/managed-by: Helm
    component: ide-proxy
    kind: service
  name: ide-proxy
  namespace: gitpod
  resourceVersion: "3607"
  uid: 29b6f750-9bb6-4e7e-9613-3f54d7bbac8a
spec:
  clusterIP: 10.43.61.46
  clusterIPs:
  - 10.43.61.46
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: gitpod
    component: ide-proxy
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
