apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-05-09T09:21:56Z"
  labels:
    kots.io/backup: velero
    kots.io/kotsadm: "true"
  name: kotsadm-minio
  namespace: gitpod
  resourceVersion: "2432"
  uid: 37d7ea85-0761-442a-a7d7-1518f4aace6d
spec:
  clusterIP: 10.43.181.76
  clusterIPs:
  - 10.43.181.76
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: service
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: kotsadm-minio
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
