apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: gitpod
    meta.helm.sh/release-namespace: gitpod
  creationTimestamp: "2023-05-09T09:31:14Z"
  labels:
    app.kubernetes.io/instance: minio
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: minio
    helm.sh/chart: minio-11.10.24
  name: minio
  namespace: gitpod
  resourceVersion: "3627"
  uid: 3aa1f45d-b9b6-40af-8efc-58d027fff9c1
spec:
  clusterIP: 10.43.152.158
  clusterIPs:
  - 10.43.152.158
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: minio-api
    port: 9000
    protocol: TCP
    targetPort: minio-api
  - name: minio-console
    port: 9001
    protocol: TCP
    targetPort: minio-console
  selector:
    app.kubernetes.io/instance: minio
    app.kubernetes.io/name: minio
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
