apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: gitpod
    meta.helm.sh/release-namespace: gitpod
  creationTimestamp: "2023-05-09T09:31:14Z"
  labels:
    app: gitpod
    app.kubernetes.io/managed-by: Helm
    component: openvsx-proxy
    kind: service
  name: openvsx-proxy
  namespace: gitpod
  resourceVersion: "3660"
  uid: 07ab6449-6aef-480e-879a-7c2ca57ab689
spec:
  clusterIP: 10.43.146.182
  clusterIPs:
  - 10.43.146.182
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: metrics
    port: 9500
    protocol: TCP
    targetPort: 9500
  selector:
    app: gitpod
    component: openvsx-proxy
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
