apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: gitpod
    meta.helm.sh/release-namespace: gitpod
  creationTimestamp: "2023-05-09T09:31:14Z"
  labels:
    app: gitpod
    app.kubernetes.io/managed-by: Helm
    component: registry-facade
    kind: service
  name: registry-facade
  namespace: gitpod
  resourceVersion: "3680"
  uid: fc3e142d-e41c-4515-8d55-6a17e60707c5
spec:
  clusterIP: 10.43.225.69
  clusterIPs:
  - 10.43.225.69
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: registry
    port: 20000
    protocol: TCP
    targetPort: 32223
  selector:
    app: gitpod
    component: registry-facade
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
