apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: gitpod
    meta.helm.sh/release-namespace: gitpod
  creationTimestamp: "2023-05-09T09:31:14Z"
  labels:
    app: gitpod
    app.kubernetes.io/managed-by: Helm
    component: ws-manager
    kind: service
  name: ws-manager
  namespace: gitpod
  resourceVersion: "3631"
  uid: 2b767850-6c2b-49b6-b957-e8ad8d35dc8d
spec:
  clusterIP: 10.43.204.129
  clusterIPs:
  - 10.43.204.129
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: rpc
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: gitpod
    component: ws-manager
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
