apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: gitpod
    meta.helm.sh/release-namespace: gitpod
  creationTimestamp: "2023-05-09T09:31:14Z"
  labels:
    app: gitpod
    app.kubernetes.io/managed-by: Helm
    component: ws-proxy
    kind: service
  name: ws-proxy
  namespace: gitpod
  resourceVersion: "3645"
  uid: 01a8f5f8-4fe0-45c7-b5c3-5f24f3c1bb1e
spec:
  clusterIP: 10.43.131.67
  clusterIPs:
  - 10.43.131.67
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http-proxy
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: https-proxy
    port: 9090
    protocol: TCP
    targetPort: 9090
  - name: metrics
    port: 9500
    protocol: TCP
    targetPort: 9500
  - name: ssh
    port: 22
    protocol: TCP
    targetPort: 2200
  selector:
    app: gitpod
    component: ws-proxy
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
