apiVersion: batch/v1
kind: CronJob
metadata:
  annotations:
    meta.helm.sh/release-name: gitpod
    meta.helm.sh/release-namespace: gitpod
  creationTimestamp: "2023-05-09T09:31:14Z"
  generation: 1
  labels:
    app: gitpod
    app.kubernetes.io/managed-by: Helm
    component: gitpod
  name: gitpod-telemetry
  namespace: gitpod
  resourceVersion: "56508"
  uid: 0c77212e-57b4-4a72-8217-c89fd53bac1f
spec:
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
      labels:
        app: gitpod
        component: gitpod
      name: gitpod-telemetry
      namespace: gitpod
    spec:
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: gitpod
            component: gitpod
          name: gitpod-telemetry
          namespace: gitpod
        spec:
          containers:
          - args:
            - send
            env:
            - name: GITPOD_INSTALLATION_VERSION
              value: release-2022.11.2.16
            - name: GITPOD_INSTALLATION_PLATFORM
              value: k3s
            - name: SERVER_URL
              value: http://server.gitpod.svc.cluster.local:9000
            image: eu.gcr.io/gitpod-core-dev/build/installation-telemetry:commit-668e50f9f635342acb4eb52115be71fa0dee2a51
            imagePullPolicy: IfNotPresent
            name: gitpod-telemetry
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          enableServiceLinks: false
          initContainers:
          - args:
            - -v
            - database
            env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  key: host
                  name: mysql
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  key: port
                  name: mysql
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: mysql
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: mysql
            - name: DB_ENCRYPTION_KEYS
              valueFrom:
                secretKeyRef:
                  key: encryptionKeys
                  name: mysql
            image: eu.gcr.io/gitpod-core-dev/build/service-waiter:commit-668e50f9f635342acb4eb52115be71fa0dee2a51
            imagePullPolicy: IfNotPresent
            name: database-waiter
            resources: {}
            securityContext:
              privileged: false
              runAsUser: 31001
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          serviceAccount: gitpod
          serviceAccountName: gitpod
          terminationGracePeriodSeconds: 30
  schedule: '@daily'
  successfulJobsHistoryLimit: 3
  suspend: false
status:
  lastScheduleTime: "2023-05-10T00:00:00Z"
  lastSuccessfulTime: "2023-05-10T00:00:13Z"
