apiVersion: apps/v1
data:
  spec:
    template:
      $patch: replace
      metadata:
        annotations:
          backup.velero.io/backup-volumes: kotsadm-minio,minio-config-dir,minio-cert-dir
        creationTimestamp: null
        labels:
          app: kotsadm-minio
          kots.io/backup: velero
          kots.io/kotsadm: "true"
      spec:
        containers:
        - command:
          - /bin/sh
          - -ce
          - /usr/bin/docker-entrypoint.sh minio -C /home/minio/.minio/ --quiet server
            /export
          env:
          - name: MINIO_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                key: accesskey
                name: kotsadm-minio
          - name: MINIO_SECRET_KEY
            valueFrom:
              secretKeyRef:
                key: secretkey
                name: kotsadm-minio
          - name: MINIO_BROWSER
            value: "on"
          - name: MINIO_UPDATE
            value: "off"
          image: minio/minio:RELEASE.2023-04-20T17-56-55Z
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /minio/health/live
              port: service
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
          name: kotsadm-minio
          ports:
          - containerPort: 9000
            name: service
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /minio/health/ready
              port: service
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 100m
              memory: 512Mi
            requests:
              cpu: 50m
              memory: 100Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /export
            name: kotsadm-minio
          - mountPath: /home/minio/.minio/
            name: minio-config-dir
          - mountPath: /.minio/
            name: minio-cert-dir
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext:
          fsGroup: 1001
          runAsUser: 1001
        terminationGracePeriodSeconds: 30
        volumes:
        - name: kotsadm-minio
          persistentVolumeClaim:
            claimName: kotsadm-minio
        - emptyDir: {}
          name: minio-config-dir
        - emptyDir: {}
          name: minio-cert-dir
kind: ControllerRevision
metadata:
  creationTimestamp: "2023-05-09T09:21:56Z"
  labels:
    app: kotsadm-minio
    controller.kubernetes.io/hash: 7b6b4bd5b5
    kots.io/backup: velero
    kots.io/kotsadm: "true"
  name: kotsadm-minio-7b6b4bd5b5
  namespace: gitpod
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: StatefulSet
    name: kotsadm-minio
    uid: c091d3ad-b45d-4e50-bd04-795a72ecbd56
  resourceVersion: "2429"
  uid: c8496450-2e2e-43ee-99af-c4ee5305d49c
revision: 1
