apiVersion: apps/v1
data:
  spec:
    template:
      $patch: replace
      metadata:
        annotations:
          gitpod.io/checksum_config: 35e84cbb015525dc3afe0e755135f4848843569bae5fa8667c78961296a47eca
        creationTimestamp: null
        labels:
          app: gitpod
          component: openvsx-proxy
        name: openvsx-proxy
        namespace: gitpod
      spec:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: gitpod.io/workload_ide
                  operator: Exists
        containers:
        - args:
          - /config/config.json
          env:
          - name: GITPOD_DOMAIN
            value: ide-lyy.one
          - name: GITPOD_INSTALLATION_SHORTNAME
            value: default
          - name: GITPOD_REGION
            value: local
          - name: HOST_URL
            value: https://ide-lyy.one
          - name: KUBE_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: KUBE_DOMAIN
            value: svc.cluster.local
          - name: LOG_LEVEL
            value: info
          image: eu.gcr.io/gitpod-core-dev/build/openvsx-proxy:commit-668e50f9f635342acb4eb52115be71fa0dee2a51
          imagePullPolicy: IfNotPresent
          name: openvsx-proxy
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 9500
            name: metrics
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /openvsx-proxy-status
              port: 8080
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 1m
              memory: 150Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /config
            name: config
        - command:
          - redis-server
          - /config/redis.conf
          env:
          - name: MASTER
            value: "true"
          image: docker.io/library/redis:6.2
          imagePullPolicy: IfNotPresent
          name: redis
          ports:
          - containerPort: 6379
            protocol: TCP
          resources:
            requests:
              cpu: 1m
              memory: 150Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /config
            name: config
          - mountPath: /data
            name: redis-data
        - args:
          - --logtostderr
          - --insecure-listen-address=[$(IP)]:9500
          - --upstream=http://127.0.0.1:9500/
          env:
          - name: IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          image: quay.io/brancz/kube-rbac-proxy:v0.12.0
          imagePullPolicy: IfNotPresent
          name: kube-rbac-proxy
          ports:
          - containerPort: 9500
            name: metrics
            protocol: TCP
          resources:
            requests:
              cpu: 1m
              memory: 30Mi
          securityContext:
            runAsGroup: 65532
            runAsNonRoot: true
            runAsUser: 65532
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: FallbackToLogsOnError
        dnsPolicy: ClusterFirst
        enableServiceLinks: false
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: openvsx-proxy
        serviceAccountName: openvsx-proxy
        terminationGracePeriodSeconds: 30
        volumes:
        - configMap:
            defaultMode: 420
            name: openvsx-proxy-config
          name: config
kind: ControllerRevision
metadata:
  annotations:
    meta.helm.sh/release-name: gitpod
    meta.helm.sh/release-namespace: gitpod
  creationTimestamp: "2023-05-09T09:31:14Z"
  labels:
    app: gitpod
    component: openvsx-proxy
    controller.kubernetes.io/hash: 78b6996b4d
  name: openvsx-proxy-78b6996b4d
  namespace: gitpod
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: StatefulSet
    name: openvsx-proxy
    uid: 2556e431-c788-4331-a9cf-50a3b6e309ee
  resourceVersion: "3771"
  uid: ecfa7070-ebf4-43d7-a7dc-36ac41f84eb4
revision: 1
