apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  annotations:
    meta.helm.sh/release-name: gitpod
    meta.helm.sh/release-namespace: gitpod
  creationTimestamp: "2023-05-09T09:31:15Z"
  generation: 1
  labels:
    app: gitpod
    app.kubernetes.io/managed-by: Helm
    component: cluster
  name: gitpod-selfsigned-issuer
  namespace: gitpod
  resourceVersion: "3932"
  uid: 01538556-bf64-4cdc-aae8-8a8f27e31d6c
spec:
  selfSigned: {}
status:
  conditions:
  - lastTransitionTime: "2023-05-09T09:31:15Z"
    observedGeneration: 1
    reason: IsReady
    status: "True"
    type: Ready
