apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kots.io/app-slug: gitpod
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"kots.io/app-slug":"gitpod"},"labels":{"app":"gitpod","component":"gitpod-installer-status","kots.io/app-slug":"gitpod","kots.io/backup":"velero"},"name":"installation-status","namespace":"gitpod"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"gitpod","component":"gitpod-installer-status"}},"strategy":{"rollingUpdate":{"maxSurge":1,"maxUnavailable":0},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"kots.io/app-slug":"gitpod"},"labels":{"app":"gitpod","component":"gitpod-installer-status","kots.io/app-slug":"gitpod","kots.io/backup":"velero"}},"spec":{"containers":[{"command":["/app/scripts/kots-installation-status.sh"],"envFrom":[{"configMapRef":{"name":"gitpod-kots-config"}}],"image":"eu.gcr.io/gitpod-core-dev/build/installer:release-2022.11.2.16","name":"installation-status","resources":{"limits":{"cpu":"500m","memory":"128Mi"}}}],"imagePullSecrets":[{"name":"gitpod-registry"}],"restartPolicy":"Always","serviceAccountName":"kotsadm"}}}}
  creationTimestamp: "2023-05-09T09:30:58Z"
  generation: 1
  labels:
    app: gitpod
    component: gitpod-installer-status
    kots.io/app-slug: gitpod
    kots.io/backup: velero
  name: installation-status
  namespace: gitpod
  resourceVersion: "8484"
  uid: bb0865d8-ea1b-437a-b0ce-b7f7bceadc08
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: gitpod
      component: gitpod-installer-status
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kots.io/app-slug: gitpod
      creationTimestamp: null
      labels:
        app: gitpod
        component: gitpod-installer-status
        kots.io/app-slug: gitpod
        kots.io/backup: velero
    spec:
      containers:
      - command:
        - /app/scripts/kots-installation-status.sh
        envFrom:
        - configMapRef:
            name: gitpod-kots-config
        image: eu.gcr.io/gitpod-core-dev/build/installer:release-2022.11.2.16
        imagePullPolicy: IfNotPresent
        name: installation-status
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: gitpod-registry
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: kotsadm
      serviceAccountName: kotsadm
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-05-09T09:30:58Z"
    lastUpdateTime: "2023-05-09T09:31:50Z"
    message: ReplicaSet "installation-status-6c88597b57" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2023-05-09T10:05:38Z"
    lastUpdateTime: "2023-05-09T10:05:38Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
