apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: "2023-05-09T09:31:14Z"
  labels:
    app: gitpod
    app.kubernetes.io/managed-by: Helm
    component: blobserve
    kind: service
  name: blobserve
  namespace: gitpod
  resourceVersion: "8267"
  uid: 3e2fd796-339f-4a10-8bc1-3626f87d99d7
subsets:
- addresses:
  - ip: 192.168.132.218
    nodeName: vultr
    targetRef:
      kind: Pod
      name: blobserve-75d764476-tsfxp
      namespace: gitpod
      uid: 33a4ad59-a1fa-44a0-8e82-0072a9159419
  ports:
  - name: service
    port: 32224
    protocol: TCP
