apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: "2023-05-09T09:31:14Z"
  labels:
    app: gitpod
    app.kubernetes.io/managed-by: Helm
    component: content-service
    kind: service
  name: content-service
  namespace: gitpod
  resourceVersion: "7985"
  uid: ec1b45e3-ff33-4bd7-9e42-2215befbef76
subsets:
- addresses:
  - ip: 192.168.132.225
    nodeName: vultr
    targetRef:
      kind: Pod
      name: content-service-685fdc4d-fg65x
      namespace: gitpod
      uid: 87412fec-b1e6-4912-be60-3cf00a0c99fb
  ports:
  - name: metrics
    port: 9500
    protocol: TCP
  - name: rpc
    port: 8080
    protocol: TCP
