apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2023-05-09T09:32:17Z"
  creationTimestamp: "2023-05-09T09:31:14Z"
  labels:
    app: gitpod
    app.kubernetes.io/managed-by: Helm
    component: db
  name: db
  namespace: gitpod
  resourceVersion: "4760"
  uid: babce3a4-423d-49fb-9c64-e4253c336c94
subsets:
- addresses:
  - ip: 192.168.132.245
    nodeName: vultr
    targetRef:
      kind: Pod
      name: mysql-0
      namespace: gitpod
      uid: 4e695631-7ae9-4fbe-a349-c5489f134765
  ports:
  - port: 3306
    protocol: TCP
