apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2023-05-09T09:31:37Z"
  creationTimestamp: "2023-05-09T09:31:14Z"
  labels:
    app: gitpod
    app.kubernetes.io/managed-by: Helm
    component: ide-metrics
    kind: service
  name: ide-metrics
  namespace: gitpod
  resourceVersion: "4542"
  uid: 1027146e-bae0-4938-818c-05e5300cd5cc
subsets:
- addresses:
  - ip: 192.168.132.223
    nodeName: vultr
    targetRef:
      kind: Pod
      name: ide-metrics-6d9889c4bb-qn27s
      namespace: gitpod
      uid: 4d503971-c42e-4151-8c46-469386514cd0
  ports:
  - name: http
    port: 3000
    protocol: TCP
