apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: "2023-05-09T09:31:14Z"
  labels:
    app: gitpod
    app.kubernetes.io/managed-by: Helm
    component: image-builder-mk3
    kind: service
  name: image-builder-mk3
  namespace: gitpod
  resourceVersion: "8164"
  uid: 110ce8b9-b55f-495d-8bc9-b653950612a2
subsets:
- addresses:
  - ip: 192.168.132.220
    nodeName: vultr
    targetRef:
      kind: Pod
      name: image-builder-mk3-6676cb685f-ztm55
      namespace: gitpod
      uid: f4ae748b-2689-4e06-b3f6-54e656531320
  ports:
  - name: service
    port: 8080
    protocol: TCP
