apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2023-05-09T09:22:23Z"
  creationTimestamp: "2023-05-09T09:21:56Z"
  labels:
    kots.io/backup: velero
    kots.io/kotsadm: "true"
  name: kotsadm-rqlite
  namespace: gitpod
  resourceVersion: "2572"
  uid: c08cc522-a756-4cac-a3a9-09d08ff555e5
subsets:
- addresses:
  - ip: 192.168.132.207
    nodeName: vultr
    targetRef:
      kind: Pod
      name: kotsadm-rqlite-0
      namespace: gitpod
      uid: 68920ff2-2a51-4b5d-96bf-6374fd7da1b8
  ports:
  - name: rqlite
    port: 4001
    protocol: TCP
