apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2023-05-09T10:05:22Z"
  creationTimestamp: "2023-05-09T09:31:14Z"
  labels:
    app.kubernetes.io/instance: minio
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: minio
    helm.sh/chart: minio-11.10.24
  name: minio
  namespace: gitpod
  resourceVersion: "8379"
  uid: afa9e73a-3cbe-4618-b4b5-f7d2d21ccb65
subsets:
- addresses:
  - ip: 192.168.132.205
    nodeName: vultr
    targetRef:
      kind: Pod
      name: minio-6968f88644-wd6q5
      namespace: gitpod
      uid: d5c7217e-9eb8-4062-9ce4-c848bc8c0206
  ports:
  - name: minio-api
    port: 9000
    protocol: TCP
  - name: minio-console
    port: 9001
    protocol: TCP
