apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2023-05-09T10:11:24Z"
  creationTimestamp: "2023-05-09T09:31:14Z"
  labels:
    app: docker-registry
    app.kubernetes.io/managed-by: Helm
    chart: docker-registry-2.2.2
    heritage: Helm
    release: docker-registry
  name: registry
  namespace: gitpod
  resourceVersion: "9015"
  uid: 34239d7c-311d-4aef-b886-b37816835b8e
subsets:
- addresses:
  - ip: 192.168.132.251
    nodeName: vultr
    targetRef:
      kind: Pod
      name: registry-849478cf8-g5jp7
      namespace: gitpod
      uid: e2b510ee-2d10-4259-9602-1525c70030cd
  ports:
  - name: https-443
    port: 5000
    protocol: TCP
