apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: "2023-05-09T09:31:14Z"
  labels:
    app: gitpod
    app.kubernetes.io/managed-by: Helm
    component: server
    kind: service
  name: server
  namespace: gitpod
  resourceVersion: "8290"
  uid: 5557c3f4-a194-4063-9c9b-6a2faa209cc2
subsets:
- addresses:
  - ip: 192.168.132.250
    nodeName: vultr
    targetRef:
      kind: Pod
      name: server-78d46f8db4-bx5jb
      namespace: gitpod
      uid: f2fe5bec-424d-4272-9345-0ec652b93905
  ports:
  - name: install-admin
    port: 9000
    protocol: TCP
  - name: debug
    port: 6060
    protocol: TCP
  - name: debugnode
    port: 9229
    protocol: TCP
  - name: http
    port: 3000
    protocol: TCP
  - name: metrics
    port: 9500
    protocol: TCP
