apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: "2023-05-09T09:31:14Z"
  labels:
    app: gitpod
    app.kubernetes.io/managed-by: Helm
    component: ws-proxy
    kind: service
  name: ws-proxy
  namespace: gitpod
  resourceVersion: "8134"
  uid: cba4a149-6404-43d7-8cca-e9eaa21c6eee
subsets:
- addresses:
  - ip: 192.168.132.255
    nodeName: vultr
    targetRef:
      kind: Pod
      name: ws-proxy-7584dfddf4-zkqgh
      namespace: gitpod
      uid: c900e7a0-aab9-4c2e-9675-9df652e10b14
  ports:
  - name: https-proxy
    port: 9090
    protocol: TCP
  - name: metrics
    port: 9500
    protocol: TCP
  - name: ssh
    port: 2200
    protocol: TCP
  - name: http-proxy
    port: 8080
    protocol: TCP
