apiVersion: apps/v1
kind: ReplicaSet
metadata:
  annotations:
    deployment.kubernetes.io/desired-replicas: "1"
    deployment.kubernetes.io/max-replicas: "2"
    deployment.kubernetes.io/revision: "1"
    kots.io/app-slug: gitpod
  creationTimestamp: "2023-05-09T09:30:58Z"
  generation: 1
  labels:
    app: gitpod
    component: gitpod-installer-status
    kots.io/app-slug: gitpod
    kots.io/backup: velero
    pod-template-hash: 6c88597b57
  name: installation-status-6c88597b57
  namespace: gitpod
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: Deployment
    name: installation-status
    uid: bb0865d8-ea1b-437a-b0ce-b7f7bceadc08
  resourceVersion: "8483"
  uid: d9cfe05d-52b9-4e3d-82ef-1669c48afec5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitpod
      component: gitpod-installer-status
      pod-template-hash: 6c88597b57
  template:
    metadata:
      annotations:
        kots.io/app-slug: gitpod
      creationTimestamp: null
      labels:
        app: gitpod
        component: gitpod-installer-status
        kots.io/app-slug: gitpod
        kots.io/backup: velero
        pod-template-hash: 6c88597b57
    spec:
      containers:
      - command:
        - /app/scripts/kots-installation-status.sh
        envFrom:
        - configMapRef:
            name: gitpod-kots-config
        image: eu.gcr.io/gitpod-core-dev/build/installer:release-2022.11.2.16
        imagePullPolicy: IfNotPresent
        name: installation-status
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: gitpod-registry
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: kotsadm
      serviceAccountName: kotsadm
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  fullyLabeledReplicas: 1
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
