apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: 7cc7f222a1e14fe750889ea7310ba79d66c16c0a7503588967108e79dd862e22
    cni.projectcalico.org/podIP: 192.168.132.225/32
    cni.projectcalico.org/podIPs: 192.168.132.225/32
    gitpod.io/checksum_config: 8ad39f6cab4975d90bb2c9bb96710cc304bb1a2e5115b6c0f9e804dbc36920ea
  creationTimestamp: "2023-05-09T10:05:00Z"
  generateName: content-service-685fdc4d-
  labels:
    app: gitpod
    component: content-service
    pod-template-hash: 685fdc4d
  name: content-service-685fdc4d-fg65x
  namespace: gitpod
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: content-service-685fdc4d
    uid: baad493e-fd53-4f1c-9114-94d8efac23b5
  resourceVersion: "7976"
  uid: 87412fec-b1e6-4912-be60-3cf00a0c99fb
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: gitpod.io/workload_meta
            operator: Exists
  containers:
  - args:
    - run
    - --config
    - /config/config.json
    env:
    - name: GITPOD_DOMAIN
      value: ide-lyy.one
    - name: GITPOD_INSTALLATION_SHORTNAME
      value: default
    - name: GITPOD_REGION
      value: local
    - name: HOST_URL
      value: https://ide-lyy.one
    - name: KUBE_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: KUBE_DOMAIN
      value: svc.cluster.local
    - name: LOG_LEVEL
      value: info
    - name: JAEGER_DISABLED
      value: "true"
    - name: GRPC_GO_RETRY
      value: "on"
    image: eu.gcr.io/gitpod-core-dev/build/content-service:commit-668e50f9f635342acb4eb52115be71fa0dee2a51
    imagePullPolicy: IfNotPresent
    name: content-service
    ports:
    - containerPort: 8080
      name: rpc
      protocol: TCP
    - containerPort: 9500
      name: metrics
      protocol: TCP
    resources:
      requests:
        cpu: 100m
        memory: 32Mi
    securityContext:
      privileged: false
      runAsUser: 1000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /config
      name: config
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-xxnzd
      readOnly: true
  - args:
    - --logtostderr
    - --insecure-listen-address=[$(IP)]:9500
    - --upstream=http://127.0.0.1:9500/
    env:
    - name: IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    image: quay.io/brancz/kube-rbac-proxy:v0.12.0
    imagePullPolicy: IfNotPresent
    name: kube-rbac-proxy
    ports:
    - containerPort: 9500
      name: metrics
      protocol: TCP
    resources:
      requests:
        cpu: 1m
        memory: 30Mi
    securityContext:
      runAsGroup: 65532
      runAsNonRoot: true
      runAsUser: 65532
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: FallbackToLogsOnError
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-xxnzd
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: false
  nodeName: vultr
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: content-service
  serviceAccountName: content-service
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - configMap:
      defaultMode: 420
      name: content-service
    name: config
  - name: kube-api-access-xxnzd
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-05-09T10:05:00Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-05-09T10:05:05Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-05-09T10:05:05Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-05-09T10:05:00Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://791ba6cc4812476a8ccb6d173817b4632c12b764339eed301b118f2477093b64
    image: eu.gcr.io/gitpod-core-dev/build/content-service:commit-668e50f9f635342acb4eb52115be71fa0dee2a51
    imageID: eu.gcr.io/gitpod-core-dev/build/content-service@sha256:d53f708c81c76198987956578e21fdf9b4f54b61f3963ae2274446608694b8e6
    lastState: {}
    name: content-service
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-05-09T10:05:04Z"
  - containerID: containerd://95ba448acd5ae3dba2f6d455f55e9c781ece673789fba77cc1bb80dd42f337f1
    image: quay.io/brancz/kube-rbac-proxy:v0.12.0
    imageID: quay.io/brancz/kube-rbac-proxy@sha256:12b82e47da1a2f5094966d4239811a5ae5c37b47e4224b1b35e57a7f02edd57a
    lastState: {}
    name: kube-rbac-proxy
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-05-09T10:05:05Z"
  hostIP: 45.77.41.206
  phase: Running
  podIP: 192.168.132.225
  podIPs:
  - ip: 192.168.132.225
  qosClass: Burstable
  startTime: "2023-05-09T10:05:00Z"
