apiVersion: v1
kind: Pod
metadata:
  annotations:
    checksum/credentials-secret: 5d9578f21abc80c539264f37439e6e9079e9f3da5a61f845590b0dfbeaaad549
    cni.projectcalico.org/containerID: e6ad6b363b252a5956122c3c7107a17f7cdb0442e8faf900cbf378321f46d074
    cni.projectcalico.org/podIP: 192.168.132.205/32
    cni.projectcalico.org/podIPs: 192.168.132.205/32
  creationTimestamp: "2023-05-09T10:05:10Z"
  generateName: minio-6968f88644-
  labels:
    app.kubernetes.io/instance: minio
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: minio
    helm.sh/chart: minio-11.10.24
    pod-template-hash: 6968f88644
  name: minio-6968f88644-wd6q5
  namespace: gitpod
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: minio-6968f88644
    uid: 8c80ad20-47c6-4590-95fd-0751e60c35dc
  resourceVersion: "8376"
  uid: d5c7217e-9eb8-4062-9ce4-c848bc8c0206
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: gitpod.io/workload_meta
            operator: Exists
  containers:
  - env:
    - name: BITNAMI_DEBUG
      value: "false"
    - name: MINIO_SCHEME
      value: http
    - name: MINIO_FORCE_NEW_KEYS
      value: "no"
    - name: MINIO_ROOT_USER
      valueFrom:
        secretKeyRef:
          key: root-user
          name: minio
    - name: MINIO_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          key: root-password
          name: minio
    - name: MINIO_BROWSER
      value: "on"
    - name: MINIO_PROMETHEUS_AUTH_TYPE
      value: public
    - name: MINIO_CONSOLE_PORT_NUMBER
      value: "9001"
    - name: MINIO_SKIP_CLIENT
      value: "yes"
    image: docker.io/bitnami/minio:2022.12.12-debian-11-r0
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 5
      httpGet:
        path: /minio/health/live
        port: minio-api
        scheme: HTTP
      initialDelaySeconds: 5
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 5
    name: minio
    ports:
    - containerPort: 9000
      name: minio-api
      protocol: TCP
    - containerPort: 9001
      name: minio-console
      protocol: TCP
    readinessProbe:
      failureThreshold: 5
      initialDelaySeconds: 5
      periodSeconds: 5
      successThreshold: 1
      tcpSocket:
        port: minio-api
      timeoutSeconds: 1
    resources:
      requests:
        memory: 2Gi
    securityContext:
      runAsNonRoot: true
      runAsUser: 1001
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /data
      name: data
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-snknd
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: vultr
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1001
  serviceAccount: minio
  serviceAccountName: minio
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: minio
  - name: kube-api-access-snknd
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-05-09T10:05:10Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-05-09T10:05:22Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-05-09T10:05:22Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-05-09T10:05:10Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://074fdacd1efd50b35b02600a00a906e14a46a0e8b615cd50f10b26758d13e11f
    image: docker.io/bitnami/minio:2022.12.12-debian-11-r0
    imageID: docker.io/bitnami/minio@sha256:d922fead4cb1a37cb976b624f297452825c6a41d073997a54eb1b86429592bd6
    lastState: {}
    name: minio
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-05-09T10:05:13Z"
  hostIP: 45.77.41.206
  phase: Running
  podIP: 192.168.132.205
  podIPs:
  - ip: 192.168.132.205
  qosClass: Burstable
  startTime: "2023-05-09T10:05:10Z"
