apiVersion: v1
data:
  kotsadm-cluster-token: YjcyNGRiODAtNGM2Mi00ZmVjLThhZGYtOTIyNmEwNmY3NGU1
kind: Secret
metadata:
  creationTimestamp: "2023-05-09T09:22:46Z"
  labels:
    kots.io/backup: velero
    kots.io/kotsadm: "true"
  name: kotsadm-cluster-token
  namespace: gitpod
  resourceVersion: "2603"
  uid: e852efb5-a231-456a-9898-530e5d594363
type: Opaque
