apiVersion: v1
data:
  rabbitmq-erlang-cookie: WlgzbTM3V0RadmRIOHp5MDNaVlo=
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: gitpod
    meta.helm.sh/release-namespace: gitpod
  creationTimestamp: "2023-05-09T09:31:14Z"
  labels:
    app: gitpod
    app.kubernetes.io/managed-by: Helm
    component: rabbitmq
  name: messagebus-erlang-cookie
  namespace: gitpod
  resourceVersion: "3507"
  uid: bb0a280e-4892-4fb4-b1cb-15700e5fe0ee
type: Opaque
