apiVersion: v1
data:
  haSharedSecret: N1ZKVHV3enVHdEJrczNlMA==
  proxyPassword: ""
  proxyUsername: ""
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: gitpod
    meta.helm.sh/release-namespace: gitpod
  creationTimestamp: "2023-05-09T09:31:14Z"
  labels:
    app: docker-registry
    app.kubernetes.io/managed-by: Helm
    chart: docker-registry-2.2.2
    heritage: Helm
    release: docker-registry
  name: registry-secret
  namespace: gitpod
  resourceVersion: "7713"
  uid: d20f1151-2395-4178-95a7-cd8177bd2f90
type: Opaque
